repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.53.0  # Latest cfn-lint version
    hooks:
    -   id: cfn-python-lint
        files: templates/.*\.(json|yml|yaml)$
